# Generated by Django 2.0.7 on 2018-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text', models.TextField(max_length=10000, verbose_name='正文')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('recent_update', models.DateTimeField(verbose_name='最近修改时间')),
                ('created', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
