# Generated by Django 2.0.7 on 2018-07-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='recent_update',
            field=models.DateTimeField(null=True, verbose_name='最近修改时间'),
        ),
    ]
