# Generated by Django 2.0.7 on 2018-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180703_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='recent_update',
        ),
        migrations.AddField(
            model_name='article',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='最近修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
